#
# Copyright (c) 2026, Realtek Semiconductor Corporation
#
# SPDX-License-Identifier: LicenseRef-Realtek-5-Clause
#

#Import('rt_config')
from building import *

cwd = GetCurrentDir()

# add the general drivers.
src = Split("""
""")

src += ['romfs.c']

CPPPATH = [cwd]




group = DefineGroup('fs', src, depend = [], CPPPATH = CPPPATH)

Return('group')