/*
 * Copyright (c) 2026, Realtek Semiconductor Corporation
 *
 * SPDX-License-Identifier: LicenseRef-Realtek-5-Clause
 */

#ifndef _SIMPLE_BLE_SERVICE_H_
#define _SIMPLE_BLE_SERVICE_H_

#ifdef __cplusplus
extern "C"  {
#endif      /* __cplusplus */

/* Add Includes here */
#include <simple_ble_config.h>
#if F_APP_GATT_SERVER_EXT_API_SUPPORT
#include <profile_server_ext.h>
#else
#include <profile_server.h>
#endif

/** @defgroup SIMP_Service Simple Bluetooth LE Service
  * @brief Simple Bluetooth LE service
  * @{
  */
/*============================================================================*
 *                              Macros
 *============================================================================*/
/** @defgroup SIMP_Service_Exported_Macros SIMP Service Exported Macros
  * @brief
  * @{
  */

#define SIMP_READ_V1                                        1 /**< Read V1 Read characteristic value index. */

#define SIMP_WRITE_V2                                       1 /**< Write V2 Write characteristic value index. */

#define SIMP_NOTIFY_INDICATE_V3_ENABLE     1      /**< V3 Notify characteristic notification enabled index. */
#define SIMP_NOTIFY_INDICATE_V3_DISABLE    2      /**< V3 Notify characteristic notification disabled index. */
#define SIMP_NOTIFY_INDICATE_V4_ENABLE     3      /**< V4 Indicate characteristic indication enabled index. */
#define SIMP_NOTIFY_INDICATE_V4_DISABLE    4      /**< V4 Indicate characteristic indication disabled index. */

#define SIMP_READ_V1_MAX_LEN               300    /**< Maximum length of V1 Read characteristic value. */

/** @} End of SIMP_Service_Exported_Macros */

/*============================================================================*
 *                              Types
 *============================================================================*/
/** @defgroup SIMP_Service_Exported_Types SIMP Service Exported Types
  * @brief
  * @{
  */
/** @defgroup SIMP_Service_Application_Parameters SIMP Service Application Parameters
  * @brief  Type of parameters set/gotten from application.
  * @{
  */
typedef enum
{
    SIMPLE_BLE_SERVICE_PARAM_V1_READ_CHAR_VAL = 0x01, /**< Parameter type for @ref simp_ble_service_set_parameter
                                                           to set V1 Read characteristic value. Maximum size is
                                                           @ref SIMP_READ_V1_MAX_LEN. */
} T_SIMP_PARAM_TYPE;

/** @} */
/** @defgroup TSIMP_WRITE_MSG SIMP Written MSG
  * @brief Simple Bluetooth LE service written msg to application.
  * @{
  */
typedef struct
{
    uint8_t opcode;
    T_WRITE_TYPE write_type;
    uint16_t len;
    uint8_t *p_value;
} TSIMP_WRITE_MSG;
/** @} End of TSIMP_WRITE_MSG */


/** @defgroup TSIMP_UPSTREAM_MSG_DATA SIMP Upstream MSG Data
  * @brief Simple Bluetooth LE service callback message content.
  * @{
  */
typedef union
{
    uint8_t notification_indification_index;
    uint8_t read_value_index;
    TSIMP_WRITE_MSG write;
} TSIMP_UPSTREAM_MSG_DATA;
/** @} End of TSIMP_UPSTREAM_MSG_DATA */

/** @defgroup TSIMP_CALLBACK_DATA  SIMP Callback Data
  * @brief Simple Bluetooth LE service data to inform application.
  * @{
  */
typedef struct
{
    uint16_t                conn_handle;
    uint16_t                cid;
    uint8_t                 conn_id;
    T_SERVICE_CALLBACK_TYPE msg_type;
    TSIMP_UPSTREAM_MSG_DATA msg_data;
} TSIMP_CALLBACK_DATA;
/** @} End of TSIMP_CALLBACK_DATA */

/** @} End of SIMP_Service_Exported_Types */
/*============================================================================*
 *                              Functions
 *============================================================================*/
/** @defgroup SIMP_Service_Exported_Functions SIMP Service Exported Functions
  * @brief
  * @{
  */

/**
  * @brief Add simple Bluetooth LE service to the Bluetooth Host.
  *
  * @param[in]   p_func  Callback when service attribute was read, write or CCCD update.
  * @return Service ID generated by the Bluetooth Host: @ref T_SERVER_ID.
  * @retval 0xFF Operation failure.
  * @retval others Service ID assigned by Bluetooth Host.
  *
  */
T_SERVER_ID simp_ble_service_add_service(void *p_func);

/**
  * @brief  Set service-related data from application.
  *
  * @param[in] param_type            Parameter type to set.
  * @param[in] len                   Value length to be set.
  * @param[in] p_value               Value to set.
  * @return Parameter set result.
  * @retval true Operation success.
  * @retval false Operation failed.
  */
bool simp_ble_service_set_parameter(T_SIMP_PARAM_TYPE param_type, uint16_t len, void *p_value);

/**
  * @brief Send notification of simple notify characteristic value.
  *
  * @param[in] conn_handle       Connection handle of current ACL link.
  * @param[in] cid               L2CAP channel ID.
  * @param[in] service_id        Service ID of service.
  * @param[in] p_value           Characteristic value to notify.
  * @param[in] length            Characteristic value length to notify.
  * @return Notification action result.
  * @retval true Operation success.
  * @retval false Operation failed.
  *
  * <b>Example usage</b>
  * \code{.c}
  *   //case1:call simp_ble_service_send_v3_notify() in xxx_write_cb()
      static T_APP_RESULT xxx_attr_write_cb(uint16_t conn_handle, uint16_t cid, T_SERVER_ID service_id,
                                            uint16_t attr_index, T_WRITE_TYPE write_type, uint16_t length,
                                            uint8_t *p_value, P_FUN_EXT_WRITE_IND_POST_PROC  *p_write_ind_post_proc)
      {
          ......
          simp_ble_service_send_v3_notify(conn_handle, cid, service_id, p_data, data_len);
          ......
      }

      //case2:call simp_ble_service_send_v3_notify() in xxx_read_cb()
      static T_APP_RESULT xxx_attr_read_cb(uint16_t conn_handle, uint16_t cid,
                                            T_SERVER_ID service_id,
                                            uint16_t attr_index,
                                            uint16_t offset, uint16_t *p_length, uint8_t **pp_value)
      {
          ......
          simp_ble_service_send_v3_notify(conn_handle, cid, service_id, p_data, data_len);
          ......
      }

      //case3:call simp_ble_service_send_v3_notify() when can not directly get conn_handle and cid
      void test()
      {
          uint8_t remote_bd_addr[6];
          T_GAP_REMOTE_ADDR_TYPE remote_bd_type;
          uint16_t cid;
          uint8_t cid_num;
          uint16_t conn_handle;
          gap_chann_get_handle(remote_bd_addr, remote_bd_type, &conn_handle);
          gap_chann_get_cid(conn_handle, 1, &cid, &cid_num);
          simp_ble_service_send_v3_notify(conn_handle, cid, service_id, p_data, data_len);
      }
  * \endcode
  */
bool simp_ble_service_send_v3_notify(uint16_t conn_handle, uint16_t cid, T_SERVER_ID service_id,
                                     void *p_value, uint16_t length);

/**
  * @brief Send indication of simple indicate characteristic value.
  *
  * @param[in] conn_handle       Connection handle of current ACL link.
  * @param[in] cid               L2CAP channel ID.
  * @param[in] service_id        Service ID of service.
  * @param[in] p_value           Characteristic value to notify.
  * @param[in] length            Characteristic value length to notify.
  * @return Indication action result.
  * @retval true Operation success.
  * @retval false Operation failed.
  *
  * <b>Example usage</b>
  * \code{.c}
  *   //case1:call simp_ble_service_send_v4_indicate() in xxx_write_cb()
      static T_APP_RESULT xxx_attr_write_cb(uint16_t conn_handle, uint16_t cid, T_SERVER_ID service_id,
                                            uint16_t attr_index, T_WRITE_TYPE write_type, uint16_t length,
                                            uint8_t *p_value, P_FUN_EXT_WRITE_IND_POST_PROC  *p_write_ind_post_proc)
      {
          ......
          simp_ble_service_send_v4_indicate(conn_handle, cid, service_id, p_data, data_len);
          ......
      }

      //case2:call simp_ble_service_send_v4_indicate() in xxx_read_cb()
      static T_APP_RESULT xxx_attr_read_cb(uint16_t conn_handle, uint16_t cid,
                                            T_SERVER_ID service_id,
                                            uint16_t attr_index,
                                            uint16_t offset, uint16_t *p_length, uint8_t **pp_value)
      {
          ......
          simp_ble_service_send_v4_indicate(conn_handle, cid, service_id, p_data, data_len);
          ......
      }

      //case3:call simp_ble_service_send_v4_indicate() when can not directly get conn_handle and cid
      void test()
      {
          uint8_t remote_bd_addr[6];
          T_GAP_REMOTE_ADDR_TYPE remote_bd_type;
          uint16_t cid;
          uint8_t cid_num;
          uint16_t conn_handle;
          gap_chann_get_handle(remote_bd_addr, remote_bd_type, &conn_handle);
          gap_chann_get_cid(conn_handle, 1, &cid, &cid_num);
          simp_ble_service_send_v4_indicate(conn_handle, cid, service_id, p_data, data_len);
      }
  * \endcode
  */
bool simp_ble_service_send_v4_indicate(uint16_t conn_handle, uint16_t cid, T_SERVER_ID service_id,
                                       void *p_value, uint16_t length);

/** @} End of SIMP_Service_Exported_Functions */

/** @} End of SIMP_Service */


#ifdef __cplusplus
}
#endif

#endif /* _SIMPLE_BLE_SERVICE_H_ */
